default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  username: postgres
  password:
  pool: 5

# development:
#   adapter: postgresql
#   encoding: unicode
#   username: postgres
#   password:
#   pool: 5
#   host: db
#   database: dota_analyzer_development

# test:
#   <<: *default
#   database: dota_analyzer_test

production:
  <<: *default
  database: dota_analyzer_production
 