default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  host: db
  database: dota_analyzer_development

test:
  <<: *default
  host: db
  database: dota_analyzer_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: dota_analyzer_production
 